name: Report
description: "Report an issue or possible bug."
labels: ["hotfix: bug"]
body:
  - type: textarea
    id: astro-info
    attributes:
      label: "Please send informations form astro."
      description: "Run the command `pnpm astro info`."
      render: Shell
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: "What browser were you using?"
      description: "FireFox, Chrome, and Safari are supported in that order. If you are using any other browser, won't do something other than what is mentioned in issues"
      options:
        - Chrome
        - Bromite/Cromite
        - Chromium
        - Firefox
        - Safari
        - Edge
        - Opera
        - Vivaldi
        - Other browsers
        - Without browser
      default: 0
    validations:
      required: true
  - type: textarea
    id: about
    attributes:
      label: "Please explain bugs whenever possible."
      placeholder: "Please use English or Japanese."
      description: "Please explain under what situation and what happend. Technical informations be helpful, but not required."
    validations:
      required: true
