blank_issues_enabled: false
contact_links:
  - name: Empty Issue
    url: https://github.com/7rs/pages/issues/new
    about: Adds a new issue without templates.
  - name: Use Discussions
    url: https://github.com/7rs/pages/discussions
    about: If you have any questions and other, please use Discord or Discussions.
  - name: Discord
    url: https://7rs.dev/d
    about: If you have any questions and other, please use Discord or Discussions.
