name: Suggestions
description: Suggestions and ideas for features.
labels: ["contribute: ideas/request"]
body:
  - type: textarea
    id: about
    attributes:
      label: About ideas or features
      description: "Tell me about features or ideas. Images and diagrams are helpful."
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
      description: "Please include any reference you have."
